name: Build
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:

  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:

      - uses: actions/checkout@v4

      - name: Build
        run: sh build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: nomad
          path: nomad
          retention-days: 14
